AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AWS API Gateway for assessment. Uses lambdas to connect with Goolge Books and GitHub.

Resources:
  # ========= User Pool =========
  ApiUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: AssessmentUserPool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
  ApiUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: AssessmentAppClient
      UserPoolId: !Ref ApiUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
Outputs:
  UserPoolId:
    Description: ID of the Cognito User Pool
    Value: !Ref ApiUserPool
  UserPoolClientId:
    Description: ID of the Cognito App Client
    Value: !Ref ApiUserPoolClient
